/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:625653d3-32a8-4596-b61f-8a90edde8844",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4AyhOIY8p",
    "aws_user_pools_web_client_id": "1a325f0pvq9o0o990uerbcnop9",
    "oauth": {
        "domain": "streetteamreactbd40b2f8-bd40b2f8-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://street-team.ngrok.io/login/,https://app.modern-musician.com/login/,https://dev.modern-musician.com/login/",
        "redirectSignOut": "https://street-team.ngrok.io/login/,https://app.modern-musician.com/login/,https://dev.modern-musician.com/login/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://kfz77j2zvrdepoh4i3gz7nhc6e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4eoxvzlo2zfu7eiobjsfkstpiq",
    "aws_cognito_login_mechanism": []
};


export default awsmobile;
